### ISSUE TITLE
Correction to Lab Azure VNET-to-VNET

### ISSUE THREAD

**Issue by wysiwyg08620** [michaelsrichter/70534ExamPrep#1]
In going through the lab, the task to "Let's look at the remotebox nsg." the command shown is:
az network nsg rule list --nsg-name jumpbox-nsg -g examprep101 -o table

This should be: 
az network nsg rule list --nsg-name AllowSSHfromEast -g examprep101 -o table

**Comment by michaelsrichter** [comment]
thanks, fixed.
